version: '3.8'

services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/docker-hirehub?replicaSet=rs0&directConnection=true
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - AUTH_SECRET=${AUTH_SECRET:-hirehub-local-docker-secret-key}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-hirehub-local-docker-secret-key}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

  mongo:
    image: mongo:7
    command: ["--replSet", "rs0"]
    container_name: mongo
    ports:
      - "27027:27017"  # Host port 27027 maps to container port 27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
