import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./components/loading";
import "./globals.css";
import { auth } from "auth";
// import SessionWrapper from "@components/SessionWrapper";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/common/header";
import SessionWrapper from "./components/sessionWrapper";
import { Toaster } from "./components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "assets/favicon.ico", // You can also use PNG or SVG
  },
};

export default async function RootLayout({ children }) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen w-full overflow-x-hidden`}>
        <SessionWrapper session={session}>
          <Suspense fallback={<Loading />}>
            <Header user={session?.user} />
            {children}
          </Suspense>
          <Toaster />
        </SessionWrapper>
      </body>
    </html>
  );
}
