import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./components/Loading";
import "./globals.css";
import { auth } from "auth";
// import SessionWrapper from "@components/SessionWrapper";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/common/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Suspense fallback={<Loading />}>
          <Header user={session?.user} profileInfo={session?.user?.role}/>
          {children}</Suspense>
        </body>
      </html>
    </SessionProvider>
  );
}
